package com.javacore.exceptionHandling;

public class TestThrows {
    public static  int divideNum(int q ,int r) throws ArithmeticException {
        int div= q/r;
        return  div;
    }
}
